import {
  Search,
  SquareLibrary,
  Bug,
  ClipboardClock,
  Gauge,
  BadgePlus,
  MonitorUp,
  Link,
  LockKeyhole,
  EyeOff,
  Eye,
  LayoutDashboard,
  FolderKanban,
  ListChecks,
  CircleDot,
  BarChart3,
  Clock,
  Settings,
  Bell,
  HelpCircle,
  ChevronLeft,
  Plus,
  Users,
  Calendar,
  MoreHorizontal,
  SlidersHorizontal,
  Leaf,
  Star,
  Rocket,
  Smartphone,
  Box,
  Layers,
  MoreVertical,
  ChevronRight,
  Check,
  Inbox,
  CheckSquare,
  ListTodo,
  Map,
  Clock3,
  Sparkles,
  Filter,
  KanbanSquare,
  ArrowUpRight,
  RefreshCw,
  Zap,
  User,
  Minus,
  Equal,
  CheckCircle2,
  AlertCircle,
  Pencil,
  ClipboardList,
  Activity,
  Maximize2,
  ChevronsUp,
  ChevronUp,
  ChevronDown,
  ChevronsDown,
  GitCommit,
} from 'lucide-react';

export const Icons = {
  search: Search,
  squareLibrary: SquareLibrary,
  bug: Bug,
  clipboardClock: ClipboardClock,
  gauge: Gauge,
  badgePlus: BadgePlus,
  monitorUp: MonitorUp,
  link: Link,
  lockKeyhole: LockKeyhole,
  eyeOff: EyeOff,
  eye: Eye,
  layoutDashboard: LayoutDashboard,
  folderKanban: FolderKanban,
  listChecks: ListChecks,
  circleDot: CircleDot,
  barChart3: BarChart3,
  clock: Clock,
  settings: Settings,
  bell: Bell,
  helpCircle: HelpCircle,
  chevronLeft: ChevronLeft,
  plus: Plus,
  users: Users,
  calendar: Calendar,
  moreHorizontal: MoreHorizontal,
  slidersHorizontal: SlidersHorizontal,
  leaf: Leaf,
  star: Star,
  rocket: Rocket,
  smartphone: Smartphone,
  box: Box,
  layers: Layers,
  moreVertical: MoreVertical,
  chevronRight: ChevronRight,
  check: Check,
  inbox: Inbox,
  checkSquare: CheckSquare,
  listTodo: ListTodo,
  map: Map,
  clock3: Clock3,
  sparkles: Sparkles,
  filter: Filter,
  kanbanSquare: KanbanSquare,
  arrowUpRight: ArrowUpRight,
  refreshCw: RefreshCw,
  zap: Zap,
  user: User,
  minus: Minus,
  equal: Equal,
  checkCircle2: CheckCircle2,
  alertCircle: AlertCircle,
  pencil: Pencil,
  clipboardList: ClipboardList,
  activity: Activity,
  maximize2: Maximize2,
  chevronsUp: ChevronsUp,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronsDown: ChevronsDown,
  gitCommit: GitCommit,
};